services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    platform: linux/amd64
    ports:
      - 8081:8081
      - 1234:1234
    environment:
      - PROTOCOL=https
    volumes:
      - dbdata:/data

volumes:
  dbdata:
